apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: datastream-web-394014
  labels:
    env: test
  name: 2-brad-2-smelly
